title: Lockdown
subtitle: A static website generator
social:
    - text: GitHub
      url: https://github.com/lockdownblog/lockdown
post-routes:
    - /post/{}/index.html
tag-page-route: tag/{}/index.html
tag-index-route: tag/index.html

